Update struct attributes files
rwehresmann/sumsub-ruby-sdk pull request #4
Opened 2021-11-29 23:51 UTC by ydakuka

I checked the available structs.

2021-11-30 01:27 UTC, rwehresmann requested changes
@ydakuka Please keep `error_response.rb` as snakecase. My idea with the `struct` package is: 

1) What we'll inform in a request we keep as camelcase because is how Sumsub API is already expecting to receive;
2) The responses we'll consume in our Ruby applications we keep as snake case because is ruby style.

And could you please reference in the PR description the relevant API docs for each structure? Just to facilitate the CR and see if everything matches the docs.

2021-11-30 21:05 UTC, ydakuka commented
I have added aliases for camelCase attributes. I think this is exactly what we need.

2021-12-01 00:26 UTC, rwehresmann commented
> I have added aliases for camelCase attributes. I think this is exactly what we need.

Why, exactly? If you could explain to me why you need that, I can think about it.  The way I see we're adding something that increases maintenance just because of personal preference in naming variables. I prefer to keep it standard.

2021-12-01 00:35 UTC, ydakuka commented
The format for defining attributes is the same for all structs. The attributes of the structs are the same as what we get from the response. You can read attribute values in both camelCase and snakecase styles.

2021-12-02 00:49 UTC, rwehresmann commented
It's a matter of input and output: Sumsub API expects the input with camelcase variables; Sumsub API output is consumed by us in our ruby applications, where we use the snake case variables. I don't see a problem with this, so I'll keep it that way.

If there is any change/problem with the structures themselves (attribute missing, spelling, etc) feel free to rebase this PR (or create a new one) with the relevant modifications, providing Sumsbub API docs relevant links with the updated structs that support those modifications.

2021-12-02 09:13 UTC, ydakuka commented
Ok, done. But it's very strange that some structs use camelCase, while others use snake_case.

2021-12-02 09:14 UTC, ydakuka commented on lib/sumsub/struct/applicant.rb
> +      attribute? :phone, Types::String
https://developers.sumsub.com/api-reference/#request-body

2021-12-02 09:14 UTC, ydakuka commented on lib/sumsub/struct/applicant_update.rb
> +      attribute? :deleted, Types::Bool
https://developers.sumsub.com/api-reference/#request-body-2

2021-12-02 09:14 UTC, ydakuka commented on lib/sumsub/struct/info.rb
> -      attribute? :phone, Types::String
https://developers.sumsub.com/api-reference/#fixedinfo-and-info-attributes

2021-12-02 23:30 UTC, ydakuka commented on lib/sumsub/types.rb
> +        :COVID_VACCINATION_FORM,
https://developers.sumsub.com/api-reference/#supported-document-types

2021-12-02 23:33 UTC, ydakuka commented on lib/sumsub/types.rb
> +        nil,
https://developers.sumsub.com/api-reference/#request-metadata-body-part-fields

2021-12-08 01:15 UTC, rwehresmann approved these changes

2021-12-08 01:15 UTC, merged

2021-12-08 01:16 UTC, ydakuka commented
Thanks.